export const FORMATIONS =  [
  { "duree": "5 j",
    "id": "1",
    "nom": "Scrum",
    "certifiant": true,
    "domain": "Méthodes agile"
  },
  { "duree": "5 j",
    "id": "2",
    "nom": "Agile à léchelle Safe",
    "certifiant": true,
    "domain": "Méthodes agile"
  },
  { "duree": "5 j",
    "id": "3",
    "nom": "Kanban",
    "certifiant": true,
    "domain": "Méthodes agile"
  },
  { "duree": "5 j",
    "id": "4",
    "nom": "Introduction de la gestion de projet",
    "certifiant": false,
    "domain": "Management de projet"
  },
  { "duree": "5 j",
    "id": "5",
    "nom": "Bon pratique de management de projet",
    "certifiant": false,
    "domain": "Management de projet"
  },
  { "duree": "5 j",
    "id": "6",
    "nom": "Communication dans un projet",
    "certifiant": false,
    "domain": "Management de projet"
  },
  { "duree": "5 j",
    "id": "7",
    "nom": "La gestion des risques",
    "certifiant": false,
    "domain": "Management de projet"
  },
  { "duree": "5 j",
    "id": "8",
    "nom": "Negociation et gestion de conflit",
    "certifiant": false,
    "domain": "Management de projet"
  },
  { "duree": "5 j",
    "id": "9",
    "nom": "Leadership",
    "certifiant": false,
    "domain": "Management de projet"
  },
  { "duree": "5 j",
    "id": "10",
    "nom": "Relation de client",
    "certifiant": false,
    "domain": "Management de projet"
  },
  { "duree": "5 j",
    "id": "11",
    "nom": "Gestion des risques",
    "certifiant": false,
    "domain": "Management de projet"
  },
  { "duree": "5 j",
    "id": "12",
    "nom": "Zoom",
    "certifiant": false,
    "domain": "Outils informatique"
  },
  { "duree": "5 j",
    "id": "13",
    "nom": "Word avancé",
    "certifiant": false,
    "domain": "Outils informatique"
  },
  { "duree": "5 j",
    "id": "14",
    "nom": "Excel avancé",
    "certifiant": false,
    "domain": "Outils informatique"
  },
  { "duree": "5 j",
    "id": "15",
    "nom": "Drive et les composants",
    "certifiant": false,
    "domain": "Outils informatique"
  },
  { "duree": "5 j",
    "id": "16",
    "nom": "Microsoft Office",
    "certifiant": false,
    "domain": "Outils informatique"
  },
  { "duree": "5 j",
    "id": "17",
    "nom": "Git",
    "certifiant": false,
    "domain": "Outils informatique"
  },
  { "duree": "5 j",
    "id": "18",
    "nom": "Notion",
    "certifiant": false,
    "domain": "Outils informatique"
  },
  { "duree": "5 j",
    "id": "19",
    "nom": "Github",
    "certifiant": false,
    "domain": "Outils informatique"
  },
  { "duree": "5 j",
    "id": "20",
    "nom": "Adobe xd",
    "certifiant": false,
    "domain": "Design"
  },
  { "duree": "5 j",
    "id": "21",
    "nom": "Adobe premier pro",
    "certifiant": false,
    "domain": "Design"
  },
  { "duree": "5 j",
    "id": "22",
    "nom": "Adobe Photoshop",
    "certifiant": false,
    "domain": "Design"
  },
  { "duree": "5 j",
    "id": "23",
    "nom": "Adobe InDesigne",
    "certifiant": false,
    "domain": "Design"
  },
  { "duree": "5 j",
    "id": "24",
    "nom": "Figma",
    "certifiant": false,
    "domain": "Design"
  },
  { "duree": "5 j",
    "id": "25",
    "nom": "Wordpress",
    "certifiant": false,
    "domain": "Creation site no code"
  },
  { "duree": "5 j",
    "id": "26",
    "nom": "Prestashop",
    "certifiant": false,
    "domain": "Creation site no code"
  },
  { "duree": "5 j",
    "id": "27",
    "nom": "Joomla",
    "certifiant": false,
    "domain": "Creation site no code"
  },
  { "duree": "5 j",
    "id": "28",
    "nom": "Drupal",
    "certifiant": false,
    "domain": "Creation site no code"
  },
  { "duree": "5 j",
    "id": "29",
    "nom": "Html CSS",
    "certifiant": false,
    "domain": "Développement"
  },
  { "duree": "5 j",
    "id": "30",
    "nom": "Algo",
    "certifiant": false,
    "domain": "Développement"
  },
  { "duree": "5 j",
    "id": "31",
    "nom": "Algo",
    "certifiant": false,
    "domain": "Développement"
  },
  { "duree": "5 j",
    "id": "32",
    "nom": "Javascript",
    "certifiant": false,
    "domain": "Développement"
  },
  { "duree": "5 j",
    "id": "33",
    "nom": "Angular",
    "certifiant": false,
    "domain": "Développement"
  },
  { "duree": "5 j",
    "id": "34",
    "nom": "PHP BDD",
    "certifiant": false,
    "domain": "Développement"
  },
  { "duree": "5 j",
    "id": "35",
    "nom": "PHP avancé",
    "certifiant": false,
    "domain": "Développement"
  },
  { "duree": "5 j",
    "id": "36",
    "nom": "PHP OBJET",
    "certifiant": false,
    "domain": "Développement"
  },
  { "duree": "5 j",
    "id": "37",
    "nom": "UML",
    "certifiant": false,
    "domain": "Développement"
  },
  { "duree": "5 j",
    "id": "38",
    "nom": "Javascript Initation ou avancé",
    "certifiant": false,
    "domain": "Développement"
  },
  { "duree": "5 j",
    "id": "39",
    "nom": "Javascript Jquery",
    "certifiant": false,
    "domain": "Développement"
  },
  { "duree": "5 j",
    "id": "40",
    "nom": "Javascript Jquery",
    "certifiant": false,
    "domain": "Développement"
  },
  { "duree": "5 j",
    "id": "41",
    "nom": "Node Js",
    "certifiant": false,
    "domain": "Développement"
  },
  { "duree": "5 j",
    "id": "42",
    "nom": "React native",
    "certifiant": false,
    "domain": "Développement Mobile"
  },
  { "duree": "5 j",
    "id": "43",
    "nom": "Ionic",
    "certifiant": false,
    "domain": "Développement Mobile"
  },
  { "duree": "5 j",
    "id": "44",
    "nom": "Android",
    "certifiant": false,
    "domain": "Développement Mobile"
  }];

